### ISSUE TITLE
'test_memoize_result' unit test failing

### ISSUE THREAD

**Issue by avats-dev** [creativecommons/cc-link-checker#104]
## Description

Unit test `test_memoize_result` failing when unit tests are run on master.

## Reproduction

1. `git clone https://github.com/creativecommons/cc-link-checker.git`
2. `cd cc-link-checker`
3. `pipenv install --dev`
4. `pipenv run pytest -v`
5. See error.

## Expectation

`test_memoize_result` should pass along with all other unit tests.

## Screenshots

**Verbose test**
![Screenshot from 2020-09-01 09-27-06](https://user-images.githubusercontent.com/35889327/91793716-97f49880-ec36-11ea-9a15-86e758ba58d6.png)

**Failure description**
![Screenshot from 2020-09-01 09-26-24](https://user-images.githubusercontent.com/35889327/91793492-f9683780-ec35-11ea-88a2-d73ea371e820.png)

## Environment

 - Device: laptop
 - OS: Ubuntu LTS 20.04 (64-bit)
 - Browser: Firefox
 - Version: 80.0 (64-bit)
 - Other info: Not needed

## Resolution

- [x] I would be interested in resolving this bug.

> But I would need guidance.

**Comment by bhumijgupta** [comment]
Hey! I was able to reproduce this error.
The main cause of the error is low request timeout in the test

https://github.com/creativecommons/cc-link-checker/blob/master/link_checker/tests/test_utils.py#L395

The reason that it was passing on CI server is because the server have high bandwidth and they can complete the request in 1 sec while the local computer request fails out in that time.
A plausible fix is to change the `timeout` parameter from 1 to 3.

Hope this helps!

**Comment by bhumijgupta** [comment]
It should be a quick fix, do let me know if you want to work on the issue.

**Comment by avats-dev** [comment]
Thanks @bhumijgupta for explaining this, it was bugging me. And yes I would like to work on this. 👍

**Comment by avats-dev** [comment]
Hey @bhumijgupta , I'm thinking of changing to `timeout=2` as this should be enough. I tested for both `2` and `3` and it was same. Previously my connection was too slow so I couldn't get it to pass for `1` but now when I'm checking , it's also passing for `1`.
